version: '3.7'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=adminuser  # At least 3 characters
      - MINIO_ROOT_PASSWORD=strongpassword  # At least 8 characters
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
    driver: local
